### ISSUE TITLE
Cursor disappears?

### ISSUE THREAD

**Issue by josephwb** [jonchang/tact#101]
I notice that immediately after I run `tact_add_taxa` (but not `tact_build_taxonomic_tree`) that my blinking cursor disappears (in fact, i see no cursor whatsoever). The only way I have gotten it back is by opening a new window.

Is this because of some python environment setting that is not released, or is it just me? I'm on Ubuntu 18.04.

FWIW the commands I run are exactly the example in the README.

**Comment by jonchang** [comment]
Thanks for the report, this has been fixed.

**Comment by josephwb** [comment]
(^_-)≡☆
