### ISSUE TITLE
Assumptions made by TACT?

### ISSUE THREAD

**Issue by jsoghigian** [jonchang/tact#172]
Hi,

I was curious what assumptions TACT means with regards to input files.  Occasionally I have noticed that some taxonomically added clades are not monophyletic; for instance, I have a subgenera column, and while this column retains its monophyly, the genera to which subgenera below do not always retain their monophyly when added to the backbone tree.

**Comment by jonchang** [comment]
Hi John, absent more information (e.g. your input files and version) it's hard to know where the issue stems from. You may find it useful to run `tact_add_taxa` in verbose mode and examining the log files. One level of verbosity `-v` will give you details about placements and two levels `-vv` will give you a lot more details.

`tact_build_taxonomic_tree --help` documents what the assumptions are for buillding taxonomic phylogenies from an inpust CSV file, which I've reproduced here:

* Each row represents a single species.
* Each column represents a taxonomic rank.
* The columns must be arranged from most inclusive to least inclusive,
  with the last column as the species name.
  - e.g. Family,Genus,Species
* Each rank must be named
* Each rank must be unique
  - OK: Cichlidae,Cichla,Cichla temensis
  - NO: Cichlidae,Cichlidae,Cichla temensis
  - NO: Cichlidae,,Cichla temensis

**Comment by jsoghigian** [comment]
Hi Jon,

I'm using the Docker version (not sure how to report an exact version number) on a Mac.

There are a small handful of genera, where if the genus contains multiple subgenera, they are not properly placed together in the tacted tree. My taxonomic tree is actually correctly reflecting the genera in question as monophyletic.  However, the tacted tree does not; it does retain the monophyly of subgenera in that genus, but not the genus itself.  

My tacted tree is based on a backbone tree that is relatively poorly sampled at the species level (~200 species out of 3600) but well sampled at the backbone level.  The tacted tree largely does maintain monophyly of genera so long as genera are present in the backbone, or do not contain subgenera.  If a genus entirely absent from the backbone tree contains subgenera, the subgenera are placed (and are monophyletic), but the genus itself is not.

In checking verbose mode, it does appear that the issue is that the subgenera are added to the tree, and then when it comes time to "add" the genus, all species are already placed.

Could this be occurring because two genera in my backbone tree are not monophyletic?  These are not the problematic genera, but I don't know if that influences how TACT treats a columns.

Could I email you the input and output files?  They are unpublished so would rather share that way.

Thank you for your time and great tool!

**Comment by jonchang** [comment]
Yeah go ahead and send me an email.

**Comment by jonchang** [comment]
I haven't heard anything so assuming this has been adequately addressed.
