### ISSUE TITLE
When installing with Linuxbrew: Failed to download resource "tact"

### ISSUE THREAD

**Issue by jsoghigian** [jonchang/tact#228]
Hi there,

Thanks again for the awesome software!

I've got a working Docker version of TACT on another machine, but I wanted to install TACT on my home WSL machine.  But I ran into a problem when trying to install with brew:
```
myusrname:~$ brew install jonchang/biology/tact
==> Installing tact from jonchang/biology
... (other preqs downloading here) ...
==> Downloading https://dl.bintray.com/jonchang/bottles-biology/tact-0.3.4.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "tact"
Download failed: https://dl.bintray.com/jonchang/bottles-biology/tact-0.3.4.x86_64_linux.bottle.tar.gz
```

I've truncated the full install messages, because there's just a lot of downloading of other files successfully.  I can add them in if you think they might be a problem, but no errors were indicated before attempting to download TACT

**Comment by jonchang** [comment]
Hi John, I'm tracking this in https://github.com/jonchang/homebrew-biology/issues/44.

**Comment by jonchang** [comment]
This should be fixed now.
