### ISSUE TITLE
duplicate taxa and error for parenthesis

### ISSUE THREAD

**Issue by pbfrandsen** [jonchang/tact#234]
Hello Jon,

I am using the most recent Docker version of TACT on MacOS and I am trying to add a lot of taxa (16,000) to a relatively sparse (~200) backbone. Maybe this is a bad idea in the first place, which would make sense as to why I'm encountering difficulty. TACT runs fine, but there are a few issues that I am having with the output tree.

1. There are duplicate taxon names, usually all clustered together away from their taxonomic ranks. Some programs won't open the tree with duplicate taxon names (e.g. FigTree), but others will (e.g. TreeGraph/iTOL).
2. When I attempt to load the tree into ape/ete3 (with any format option in ete3), I get an error about parenthesis not matching. This is curious since the GUIs seem to open it fine. It doesn't matter which newick format code I use in ete3, I continue to get the error.
3. It looks like the output tree is not ultrametric, at least how it is displayed in iTOL or TreeGraph. If I export from iTOL it seems to fix the issue with the parentheses, but it is then no longer ultrametric.

Do you have any ideas for these issues? I am happy to send my input files to you via email if that would help.

Many thanks,
Paul

**Comment by pbfrandsen** [comment]
Ok, update. The parenthesis issue (#2 above) was my fault. I had a bad taxon name. I can now read the tree into ape. It still doesn't recognize it as ultrametric, but I think it is very close because downstream analysis in BAMM seems to work fine. I am still experiencing the issue with some taxa being placed multiple times in the tree. It is only a handful so I manually changed the names, but it would be great to know why this might be happening. They aren't duplicated in my taxonomy file so I'm unsure exactly where the problem is arising. thank you.

**Comment by jonchang** [comment]
Hi Paul, thanks for writing. Could you please email me send your data files? The duplicate taxon name issue in particular is very curious.

**Comment by jonchang** [comment]
Feel free to re-open this if you are still encountering the issue.
